apiVersion: apps/v1  # Kubernetes API version for deployments
kind: Deployment     # Type of object (Deployment = runs your app)
metadata:
  name: multimodal-search  # Name of deployment (used in kubectl)
spec:
  replicas: 2  # Number of running containers (for scaling & reliability)

  selector:
    matchLabels:
      app: multimodal-search  # Must match pod labels below

  template:
    metadata:
      labels:
        app: multimodal-search  # Labels used by service to find pods

    spec:
      containers:
        - name: app  # Container name inside pod

          image: shreyaraju/multimodal-search:latest
          # Docker image that Kubernetes will pull

          ports:
            - containerPort: 8000
            # Port where FastAPI runs inside container

          env:
            # ----------------------------
            # ENV VARIABLES FROM SECRET
            # ----------------------------

            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pinecone-secret
                  key: PINECONE_API_KEY

            - name: PINECONE_ENV
              valueFrom:
                secretKeyRef:
                  name: pinecone-secret
                  key: PINECONE_ENV

            - name: PINECONE_INDEX
              valueFrom:
                secretKeyRef:
                  name: pinecone-secret
                  key: PINECONE_INDEX

          resources:
            # Optional but production-grade
            limits:
              memory: "512Mi"
              cpu: "500m"