apiVersion: v1  # Core Kubernetes API
kind: Service   # Exposes your deployment to network

metadata:
  name: multimodal-search-service  # Service name

spec:
  selector:
    app: multimodal-search  # Connects to pods with same label

  type: LoadBalancer  
  # Exposes service externally (cloud) OR NodePort locally

  ports:
    - protocol: TCP   # Communication protocol
      port: 80        # External port (what users see)
      targetPort: 8000 # Internal container port (FastAPI)